micronaut:
  application:
    name: shiptracker
  jcache:
    enabled: false
  caches:
    teqplay:
      listen-to-evictions: true
      listen-to-removals: true
      maximum-size: 1
  session:
    http:
      cookie: true
      header: true
  http:
    services:
      teqplay:
        url:
  executors:
    blocking:
      virtual: true

teqplay:
  username: chowmichaelworkmail@gmail.com
  password: yZ6zEdu%jiQFd
