micronaut:
  application:
    name: shiptracker
  session:
    http:
      cookie: true
      header: true
  http:
    services:
      teqplay:
        url: https://backenddev.teqplay.nl
  executors:
    blocking:
      virtual: true

teqplay:
  username: chowmichaelworkmail@gmail.com
  password: yZ6zEdu%jiQFd
