micronaut:
  application:
    name: shiptracker
  jcache:
    enabled: false
  caches:
    teqplay:
      listen-to-evictions: true
      listen-to-removals: true
      maximum-size: 1
  session:
    http:
      cookie: true
      header: true
  http:
    services:
      teqplay:
        url: https://backenddev.teqplay.nl
        read-timeout: 20m
        thread-factory: reactor.core.scheduler.VirtualThreadFactory
        connect-timeout: 15s
        allow-block-event-loop: true
        exception-on-error-status: true
        log-level: off
        max-content-length: 120000000
  executors:
    blocking:
      virtual: true

mongodb:
  package-names:
    - com.example.entity
  uri: mongodb://user:password@localhost:27017/teqplay


teqplay:
  username: chowmichaelworkmail@gmail.com
  password: yZ6zEdu%jiQFd
